#Auto generate Debian Cloud Image with cloud-init, using gitlab ci

### Created at 2022-02-27 23:14:50 GMT+08:00
### Author:   <evsio0n>
### Email:    <bbq2001820@gmail.com>

---
stages:
  - test
  - build

default:
  tags:
    - debian

buster:test:
  stage: test
  script:
    - |
      echo -------------------
      echo "Debootstrap bullseye"
      echo -------------------
    - sed -i 's/deb.debian.org/mirrors.xtom.com.hk/g' /etc/apt/sources.list
    - |
      echo -------------------
      echo "Clean loopback device"
      echo -------------------
    - losetup -D /dev/loop0
    - >
      apt-get update && apt-get install -y
      debootstrap qemu-utils qemu-system genisoimage sudo mount fdisk
    - |
      mkdir ./debian-image
      cd ./debian-image
      echo -------------------
      echo "Create loop image "
      echo -------------------
      dd if=/dev/zero of=debian-image.img bs=1M count=0 seek=10240 status=progress
      echo -------------------
      echo "Make temp mount point"
      echo -------------------
      losetup -f debian-image.img
      sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | sudo fdisk ./debian-image.img
      o # clear the in memory partition table
      n # new partition
      p # primary partition
      1 # partition number 1 
      # default - start at beginning of disk
      +512M # 512 MB boot parttion
      n # new partition
      p # primary partition
      2 # partion number 2
      # default, start immediately after preceding partition
      # default, extend partition to end of disk
      a # make a partition bootable
      1 # bootable partition is partition 1 -- /dev/loop0p1
      p # print the in-memory partition table
      w # write the partition table
      q # and we're done
      EOF
  allow_failure: true


buster:clean:
  stage: test
